### ISSUE TITLE
API to Communicate Input Parameters of LIDAR Utilities

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/rialto-geopackage#39]
Need the ability for client-side to request a data structure defining required and optional parameters to back-end LIDAR utilities. Implement as command-line option:

ossim-hlz --request-params
ossim-viewshed --request-params

This will output (to stdout? to a text file?) a JSON-formatted lsit of params with names, types, ranges (if applicable), and descriptions. For example, for HLZ:

{
"ROI": {enum : ("geographic", "image") },
"LZ radius (meters)": double,
"observer lat (deg)": double,

"observer lon (deg)": double,
"optional": {
"reticle size": int,
"lut file": string
},
"aircraft" : {enum : ("Blackhawk", "Chinook") }
}

How to structure conditional items? For example, if the user selects ROI = geographic, the UI should add fields for min and max lat and lon to the form.

copied over from https://github.com/radiantbluetechnologies/omar-agc-pm/issues/123

**Comment by oscarkramer** [comment]
The JSON format of the API spec passed to the client upon request will be a flexible format that permits specifying various input types, optional fields, and conditional fields depending on other inputs. The JSON stream will be returned via the command line:

`<app-name> --request-api`

The JSON returned will consist of a field list with the following format:

#### Field List Template
```
{
  "<field-name-1>" : { <field object 1> },
  "<field-name-2>" : { <field object 2> },
  ...
  "<field-name-n>" : { <field object n> }
}
```

#### Field Object Template
```
{ 	
  "required" : <boolean>,
  "description" : <string>,
  "data type" : "int"|"float"|"boolean"|"enum"|"string",
```
If data type is "int" or "float":
```
  "range" : [ <min> , <max> ],
```

If data type is enum, there are two options: simple enums (array of strings):
```
  "enums" : [ "<enum-string-1>", "<enum-string-2>", ... , "<enum-string-N>" ]
```
 or compound enums (array of objects):
```
  "enums" : [ {<enum-object-1>}, {<enum-object-2>}, ... , {<enum-object-N>} ]
```
where the `<enum-object>` repeats the same format as the top-level field-list above. 
Finally the closing JSON top-level object bracket:
```
}
```

**Comment by oscarkramer** [comment]
Following template/spec in https://github.com/radiantbluetechnologies/rialto-geopackage/blob/master/wps/options_schema.txt

**Comment by oscarkramer** [comment]
Do we really need specific names like "position" (now "geographic-2d") as a datatype? Why not generalize to be "xy" for 2D double, "xyz" for 3D, etc. So position, and FOV (start,end) would share the same datatype.

**Comment by mpgerlek** [comment]
Because the UI needs to know whether to make the user drop a point on the map (position) vs just enter two numbers in a text box (e.g. for a FOV)

This is where we begin to flail about on the slippery slope. We do want the UI to be smart about some things, such as operation needing a bbox, but not smart about other things, such as needing a time of day........

**Comment by oscarkramer** [comment]
Ah, now I appreciate the need for the client-side to dictate the datatypes: "geographic-2D" ("position") is achieved by clicking on the map; "bbox" by drawing a rect on the map, etc. And the slippery slope: should range radius and FOV be distinct datatypes to suggest drawing them on the map? That's up to you so I'll let you decide what datatypes are needed. I'll fill in any missing quantities that are needed and make sense to make specific (versus generic "int" or "double"). I'll change back the few I had modified yesterday except "position" to "geographic-2D" since position can be 2D or 3D and in various coord systems. Or we can agree that all positions are in geographic coords (bbox included).

**Comment by oscarkramer** [comment]
Just committed code to OSSIM repo for this. Need to add the following to your ossim_preferences file:
```
ossim_share_directory: $(OSSIM_INSTALL_DIR)/share
```
After SVN update of OSSIM trunk and build, run command-line:
```
ossim-viewshed --request-api [<filename>]
```
If `<filename>` is ommitted, output goes to stdout.
I believe the JSON files in the OSSIM repo are functional. These will necessarily be the controlling documents (not the examples given in github).
