### ISSUE TITLE
make all fails (osx)

### ISSUE THREAD

**Issue by mamayoleksandr** [radiantbluetechnologies/rialto-geopackage#41]
Here is result of make all:

*make all
cd vendor/gtest-1.7.0/ ; \
        cmake -G "Unix Makefiles" . ; \
        make
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mamay/projects/github/rialto-geopackage/rialto-geopackage/vendor/gtest-1.7.0
[ 50%] Built target gtest
[100%] Built target gtest_main
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src all
c++ -g -std=c++11 -fPIC -O3 -I ../include -I /usr/local/opt/pdal-09dev/include -c -o obj/Event.o  Event.cpp
c++ -g -std=c++11 -fPIC -O3 -I ../include -I /usr/local/opt/pdal-09dev/include -c -o obj/GeoPackage.o  GeoPackage.cpp
c++ -g -std=c++11 -fPIC -O3 -I ../include -I /usr/local/opt/pdal-09dev/include -c -o obj/GeoPackageReader.o  GeoPackageReader.cpp
c++ -g -std=c++11 -fPIC -O3 -I ../include -I /usr/local/opt/pdal-09dev/include -c -o obj/RialtoWriter.o  RialtoWriter.cpp
c++ -g -std=c++11 -fPIC -O3 -I ../include -I /usr/local/opt/pdal-09dev/include -c -o obj/GeoPackageCommon.o  GeoPackageCommon.cpp
c++ -g -std=c++11 -fPIC -O3 -I ../include -I /usr/local/opt/pdal-09dev/include -c -o obj/GeoPackageWriter.o  GeoPackageWriter.cpp
c++ -g -std=c++11 -fPIC -O3 -I ../include -I /usr/local/opt/pdal-09dev/include -c -o obj/WritableTileCommon.o  WritableTileCommon.cpp
c++ -g -std=c++11 -fPIC -O3 -I ../include -I /usr/local/opt/pdal-09dev/include -c -o obj/GeoPackageManager.o  GeoPackageManager.cpp
c++ -g -std=c++11 -fPIC -O3 -I ../include -I /usr/local/opt/pdal-09dev/include -c -o obj/RialtoReader.o  RialtoReader.cpp
c++ -shared -L/usr/local/opt/pdal-09dev/lib -o obj/librialto.so obj/Event.o obj/GeoPackage.o obj/GeoPackageReader.o obj/RialtoWriter.o obj/GeoPackageCommon.o obj/GeoPackageWriter.o obj/WritableTileCommon.o obj/GeoPackageManager.o obj/RialtoReader.o -lboost_filesystem -lsqlite3 -lpdalcpp -lpdal_util
Undefined symbols for architecture x86_64:
  "boost::filesystem::path::stem() const", referenced from:
      rialto::RialtoWriter::processOptions(pdal::Options const&) in RialtoWriter.o
      rialto::RialtoReader::processOptions(pdal::Options const&) in RialtoReader.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]:  [obj/librialto.so] Error 1
make:  [rialto_lib] Error 2*

pdal verison: pdal (PDAL 1.0.0.b1 (1b8c75))

**Comment by mpgerlek** [comment]
I've just pushed some changes, try it now and let me know.

(Note that on `master` I'm normally using SCons instead of Make -- I'm keeping Make alive as needed, but I don't test nightly with it.)

**Comment by mamayoleksandr** [comment]
Thanks, latest version  built fine with osgeo/osgeo4mac/pdal-09dev and install path /usr/local
