### ISSUE TITLE
Ossim tools not generating JSON APIs?

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/rialto-geopackage#60]
I don't think the version of ossim-viewshed on the svn trunk is exporting the JSON API files.

**Comment by oscarkramer** [comment]
Really?

ossim-view --request-api [<filename>]   ?


________________________________

**Comment by mpgerlek** [comment]
Yes (I sent you mail about that on Friday I think(

-mpg



On Jul 27, 2015, at 9:11 AM, Oscar Kramer <notifications@github.com<mailto:notifications@github.com>> wrote:

Really?

ossim-view --request-api [<filename>] ?


________________________________
